### ISSUE TITLE
import dictregister doesn't get you to DictRegister class

### ISSUE THREAD

**Issue by Jeff17Robbins** [lgiordani/dictregister#1]
> > > import dictregister
> > > dir(dictregister)
> > > ['**author**', '**builtins**', '**doc**', '**email**', '**file**', '**name**', '**package**', '**path**', '**version**', 'dictregister']
> > > import dictregister.dictregister
> > > dir(dictregister.dictregister)
> > > ['DictRegister', '**builtins**', '**doc**', '**file**', '**name**', '**package**', 'collections', 'six']

So if I try to use dictregister per the documentation, I get an error:

> > > import dictregister
> > > d = dictregister.DictRegister()
> > > Traceback (most recent call last):
> > >   File "<interactive input>", line 1, in <module>
> > > AttributeError: 'module' object has no attribute 'DictRegister'

As you can see, DictRegister is buried one level down.  Perhaps the **init**.py file needs to do something to expose the dictregister.py file as part of the module?

**Comment by lgiordani** [comment]
You are right, I'm going to fix it. Thanks!

**Comment by lgiordani** [comment]
Fixed in 0.9.2. 0.9.1 works too, but only for Python 2.7, sorry for the double version, I forgot to run tox.
