### ISSUE TITLE
README.rst appears unformatted on PyPI

### ISSUE THREAD

**Issue by msabramo** [lgiordani/dictregister#3]
https://pypi.python.org/pypi/dictregister

It's not rendering as RST. Usually this is because of a validation error of some sort, though I didn't see any warnings or errors when I ran `rst2html` (from docutils) on the `README.rst` on git master.

**Comment by lgiordani** [comment]
The `dictregister` project is not really in use anywhere, and I'm not actively maintaining it anymore, so I'm going to close the PR without merging it. Thanks anyway!
